steps:
  # - name: node
  #   entrypoint: yarn
  #   id: install
  #   args: ["install"]
  - name: bash
    id: envsubst
    env:
      - 'VITE_APP_HOST=${_VITE_APP_HOST}'
      - 'VITE_APP_KAKAO_API_KEY=${_VITE_APP_KAKAO_API_KEY}'
      - 'VITE_APP_API_HOST=${_VITE_APP_API_HOST}'
    script: |
        #!/usr/bin/env bash
        touch .env && envsubst < .env.template > .env
  - name: node
    entrypoint: yarn
    args: ["run", "build"]
    waitFor:
      # - install
      - envsubst